apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: ghost-pod-storage
    labels:
        app: ghost
        part: storage
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi