apiVersion: apps/v1
kind: Deployment
metadata:
    name: matrix
spec:
    replicas: 1
    strategy: 
        type: Recreate
    selector:
        matchLabels:
            app: matrix
    template:
        metadata:
            labels:
                app: matrix
        spec:
            # nodeSelector:
            #   node: prempt
            containers:
                - name: matrix
                  image: gcr.io/personalpage-286518/matrix
                  ports:
                      - containerPort: 8008
---
apiVersion: v1
kind: Service
metadata:
  name: matrix-server
spec:
  ports:
  - port: 80
    targetPort: 8008
  selector:
    app: matrix